# Generated by Django 4.2.23 on 2025-09-25 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("CarbonCastRESTAPI", "0003_optimize_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="emissionactual",
            name="emission_region_ts_idx",
        ),
        migrations.RemoveIndex(
            model_name="forecast96",
            name="forecast_region_type_ts_idx",
        ),
    ]
