# Generated by Django 4.2.5 on 2026-07-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonCastRESTAPI', '0006_metric_type_and_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emissionactual',
            new_name='CarbonCastR_region_772d82_idx',
            old_name='emission_region_metric_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='forecast96',
            new_name='CarbonCastR_region_b2c5e9_idx',
            old_name='forecast_region_metric_ts_idx',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
