FROM python:3.11.4-alpine

WORKDIR /CarbonCast

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./src/CarbonCastAPI/ /CarbonCast/src/CarbonCastAPI/
COPY ./real_time/ /CarbonCast/real_time/

RUN pip install -r src/CarbonCastAPI/requirements.txt
RUN python src/CarbonCastAPI/manage.py makemigrations
RUN python src/CarbonCastAPI/manage.py migrate

ENTRYPOINT ["python", "src/CarbonCastAPI/manage.py", "runserver", "0.0.0.0:8000"]

EXPOSE 8000