# Generated by Django 4.2.4 on 2023-08-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonCastRESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password_checked',
            field=models.BooleanField(default=False),
        ),
    ]
