# Generated by Django 4.2.5 on 2025-08-23 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CarbonCastRESTAPI", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(db_index=True, max_length=32)),
                ("ts", models.DateTimeField(db_index=True)),
                ("temp", models.FloatField(blank=True, null=True)),
                ("data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "ts"], name="CarbonCastR_region_d2a654_idx"
                    )
                ],
                "unique_together": {("region", "ts")},
            },
        ),
        migrations.CreateModel(
            name="Forecast96",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(db_index=True, max_length=32)),
                ("ts", models.DateTimeField(db_index=True)),
                ("value", models.FloatField()),
                ("forecast_type", models.CharField(default="lifecycle", max_length=32)),
                ("data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "ts", "forecast_type"],
                        name="CarbonCastR_region_d31bfb_idx",
                    )
                ],
                "unique_together": {("region", "ts", "forecast_type")},
            },
        ),
        migrations.CreateModel(
            name="EmissionActual",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(db_index=True, max_length=32)),
                ("ts", models.DateTimeField(db_index=True)),
                ("lifecycle", models.FloatField(blank=True, null=True)),
                ("direct", models.FloatField(blank=True, null=True)),
                (
                    "source_file",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("data", models.JSONField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["region", "ts"], name="CarbonCastR_region_c3d3c5_idx"
                    )
                ],
                "unique_together": {("region", "ts")},
            },
        ),
    ]
