# Generated by Django 4.2.4 on 2023-09-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarbonCastRESTAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='otp_qrcode_image',
            field=models.TextField(null=True),
        ),
    ]
