#!/usr/bin/env python3
"""
Dynamic Trigger System for RDA Automation

This module implements the dynamic batch processing logic that triggers when request count
drops below 10. It provides intelligent batching strategies to maximize the 10-request
limit efficiently and responds immediately to available capacity.

Key Features:
- Event-driven triggering when request count < 10
- Intelligent batch size calculation (1-10 requests based on available slots)
- Immediate upload automation when capacity becomes available
- Integration with enhanced request monitoring system
- Optimal batch size calculation based on available capacity
- Predictive capacity management and submission timing strategies
"""

import os
import sys
import json
import time
import logging
import threading
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Callable, Tuple
from dataclasses import dataclass, asdict, field
from enum import Enum
from collections import deque
import asyncio

# Add current directory to path for imports
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from logger_utils import get_logger

from automation.event_system import (
    EventDispatcher, EventType, EventPriority, BaseEvent,
    create_event_dispatcher, create_request_count_filter
)
from automation.enhanced_request_monitor import EnhancedRequestMonitor
from automation.capacity_manager import CapacityManager, CapacityLevel
from automation.monitoring_config import EnhancedMonitoringConfig
from automation.rate_limiter import RateLimiter, RateLimitConfig, create_rate_limiter
from automation.error_handler import ErrorHandler, ErrorHandlingConfig, create_error_handler
from automation.request_throttler import RequestThrottler, ThrottlingConfig, create_request_throttler


class TriggerType(Enum):
    """Types of dynamic triggers."""
    CAPACITY_AVAILABLE = "capacity_available"
    LOW_REQUEST_COUNT = "low_request_count"
    IMMEDIATE_FILL = "immediate_fill"
    PREDICTIVE_UPLOAD = "predictive_upload"
    EMERGENCY_CAPACITY = "emergency_capacity"


class TriggerUrgency(Enum):
    """Urgency levels for triggers."""
    LOW = "low"
    NORMAL = "normal"
    HIGH = "high"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class TriggerCondition:
    """Defines conditions for triggering dynamic processing."""
    trigger_type: TriggerType
    condition_name: str
    threshold_value: int
    comparison_operator: str  # "less_than", "equals", "greater_than", etc.
    urgency_level: TriggerUrgency
    max_batch_size: int
    enabled: bool = True
    cooldown_seconds: int = 30
    last_triggered: Optional[str] = None


@dataclass
class BatchCalculation:
    """Result of batch size calculation."""
    recommended_batch_size: int
    available_slots: int
    current_request_count: int
    calculation_strategy: str
    confidence_score: float
    estimated_processing_time: Optional[float] = None
    risk_assessment: str = "low"


@dataclass
class TriggerEvent:
    """Event generated by dynamic trigger system."""
    trigger_id: str
    trigger_type: TriggerType
    trigger_condition: TriggerCondition
    batch_calculation: BatchCalculation
    trigger_reason: str
    suggested_actions: List[str]
    urgency_level: TriggerUrgency
    timestamp: str
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class TriggerStatistics:
    """Statistics for trigger system performance."""
    total_triggers_fired: int = 0
    successful_triggers: int = 0
    failed_triggers: int = 0
    average_response_time: float = 0.0
    triggers_by_type: Dict[str, int] = field(default_factory=dict)
    last_trigger_time: Optional[str] = None
    system_uptime: float = 0.0


class DynamicTriggerSystem:
    """
    Dynamic trigger system that responds to request count changes and triggers
    intelligent batch processing to maintain optimal 10-request capacity.
    
    This system integrates with the enhanced request monitor and capacity manager
    to provide immediate response when request slots become available.
    """
    
    def __init__(self,
                 enhanced_monitor: Optional[EnhancedRequestMonitor] = None,
                 capacity_manager: Optional[CapacityManager] = None,
                 event_dispatcher: Optional[EventDispatcher] = None,
                 config: Optional[Dict[str, Any]] = None,
                 rate_limiter: Optional[RateLimiter] = None,
                 error_handler: Optional[ErrorHandler] = None,
                 request_throttler: Optional[RequestThrottler] = None):
        """
        Initialize the Dynamic Trigger System.
        
        Args:
            enhanced_monitor: Enhanced request monitor for event subscription
            capacity_manager: Capacity manager for upload automation
            event_dispatcher: Event dispatcher for notifications
            config: Configuration dictionary
            rate_limiter: Rate limiter for API request management
            error_handler: Error handler for comprehensive error management
            request_throttler: Request throttler for intelligent queuing
        """
        self.logger = self._setup_logging()
        self.config = config or self._get_default_config()
        
        # Core components
        self.enhanced_monitor = enhanced_monitor
        self.capacity_manager = capacity_manager
        self.event_dispatcher = event_dispatcher or create_event_dispatcher()
        
        # Rate limiting and error handling components
        self.rate_limiter = rate_limiter or self._create_default_rate_limiter()
        self.error_handler = error_handler or self._create_default_error_handler()
        self.request_throttler = request_throttler or self._create_default_request_throttler()
        
        # Set up integrations between components
        self._setup_rate_limiting_integrations()
        
        # Trigger system state
        self.system_active = False
        self.trigger_thread: Optional[threading.Thread] = None
        self.start_time: Optional[float] = None
        
        # Trigger conditions
        self.trigger_conditions = self._initialize_trigger_conditions()
        self.active_triggers: Dict[str, TriggerEvent] = {}
        self.trigger_history: deque = deque(maxlen=100)
        
        # Statistics and monitoring
        self.statistics = TriggerStatistics()
        self.performance_metrics: deque = deque(maxlen=50)
        
        # Threading and synchronization
        self.trigger_lock = threading.RLock()
        self.processing_callbacks: List[Callable] = []
        
        # Integration components (set by integration layer)
        self.batch_system = None
        self.queue_manager = None
        
        self.logger.info("DynamicTriggerSystem initialized with rate limiting and error handling")
    
    def _setup_logging(self) -> logging.Logger:
        """Set up logging for this component using centralized configuration."""
        return get_logger('rda_automation.dynamic_trigger_system', level=logging.INFO)
    
    def _get_default_config(self) -> Dict[str, Any]:
        """Get default configuration for dynamic trigger system."""
        return {
            "enabled": True,
            "response_time_target_ms": 500,
            "max_concurrent_triggers": 3,
            "batch_optimization_enabled": True,
            "predictive_triggering_enabled": True,
            "emergency_mode_enabled": True,
            "trigger_cooldown_seconds": 30,
            "max_batch_size": 10,
            "min_batch_size": 1,
            "confidence_threshold": 0.7,
            "risk_tolerance": "medium",
            "rate_limiting_enabled": True,
            "error_handling_enabled": True,
            "request_throttling_enabled": True,
            "respect_api_limits": True,
            "adaptive_rate_limiting": True
        }
    
    def _create_default_rate_limiter(self) -> RateLimiter:
        """Create default rate limiter configuration."""
        rate_config = RateLimitConfig(
            requests_per_minute=10,  # RDA API limit
            requests_per_hour=600,
            adaptive_enabled=self.config.get("adaptive_rate_limiting", True),
            circuit_breaker_enabled=True,
            failure_threshold=5,
            recovery_timeout_seconds=300
        )
        return create_rate_limiter(rate_config)
    
    def _create_default_error_handler(self) -> ErrorHandler:
        """Create default error handler configuration."""
        error_config = ErrorHandlingConfig(
            default_max_retries=3,
            rate_limit_base_delay=60.0,
            circuit_breaker_enabled=True,
            graceful_degradation_enabled=True,
            pattern_recognition_enabled=True
        )
        return create_error_handler(error_config)
    
    def _create_default_request_throttler(self) -> RequestThrottler:
        """Create default request throttler configuration."""
        throttle_config = ThrottlingConfig(
            max_queue_size=100,
            max_concurrent_requests=3,  # Conservative for RDA API
            adaptive_throttling=True,
            rate_limiter_integration=True,
            error_handler_integration=True,
            min_request_interval_seconds=6.0,  # 10 req/min = 6s interval
            max_request_interval_seconds=60.0
        )
        return create_request_throttler(throttle_config)
    
    def _setup_rate_limiting_integrations(self):
        """Set up integrations between rate limiting components."""
        # Connect error handler and rate limiter
        self.error_handler.set_integrations(
            rate_limiter=self.rate_limiter,
            circuit_breaker=None  # Could add circuit breaker later
        )
        
        # Connect request throttler with rate limiter and error handler
        self.request_throttler.set_integrations(
            rate_limiter=self.rate_limiter,
            error_handler=self.error_handler,
            circuit_breaker=None
        )
        
        # Add callbacks for monitoring
        self.rate_limiter.add_rate_limit_callback(self._handle_rate_limit_event)
        self.error_handler.add_error_callback(self._handle_error_event)
        self.request_throttler.add_request_callback(self._handle_throttling_event)
    
    def _initialize_trigger_conditions(self) -> List[TriggerCondition]:
        """Initialize default trigger conditions."""
        conditions = [
            # Primary trigger: Any available capacity
            TriggerCondition(
                trigger_type=TriggerType.CAPACITY_AVAILABLE,
                condition_name="any_capacity_available",
                threshold_value=10,
                comparison_operator="less_than",
                urgency_level=TriggerUrgency.HIGH,
                max_batch_size=10,
                cooldown_seconds=15
            ),
            
            # Low request count trigger
            TriggerCondition(
                trigger_type=TriggerType.LOW_REQUEST_COUNT,
                condition_name="low_request_count",
                threshold_value=5,
                comparison_operator="less_than_or_equal",
                urgency_level=TriggerUrgency.HIGH,
                max_batch_size=8,
                cooldown_seconds=20
            ),
            
            # Immediate fill trigger for very low counts
            TriggerCondition(
                trigger_type=TriggerType.IMMEDIATE_FILL,
                condition_name="immediate_fill_needed",
                threshold_value=3,
                comparison_operator="less_than_or_equal",
                urgency_level=TriggerUrgency.CRITICAL,
                max_batch_size=10,
                cooldown_seconds=10
            ),
            
            # Predictive upload trigger
            TriggerCondition(
                trigger_type=TriggerType.PREDICTIVE_UPLOAD,
                condition_name="predictive_capacity_drop",
                threshold_value=8,
                comparison_operator="less_than_or_equal",
                urgency_level=TriggerUrgency.NORMAL,
                max_batch_size=5,
                cooldown_seconds=45
            ),
            
            # Emergency capacity trigger
            TriggerCondition(
                trigger_type=TriggerType.EMERGENCY_CAPACITY,
                condition_name="emergency_low_capacity",
                threshold_value=1,
                comparison_operator="less_than_or_equal",
                urgency_level=TriggerUrgency.EMERGENCY,
                max_batch_size=10,
                cooldown_seconds=5
            )
        ]
        
        return conditions
    
    def set_integration_components(self, 
                                 batch_system=None, 
                                 queue_manager=None):
        """
        Set integration components.
        
        Args:
            batch_system: BatchAutomationSystem instance
            queue_manager: IntelligentQueueManager instance
        """
        self.batch_system = batch_system
        self.queue_manager = queue_manager
        
        self.logger.info("✅ Integration components configured for dynamic trigger system")
    
    def subscribe_to_monitoring_events(self):
        """Subscribe to enhanced monitoring events."""
        if not self.enhanced_monitor or not self.event_dispatcher:
            self.logger.warning("⚠️ Cannot subscribe to events - missing components")
            return
        
        try:
            # Subscribe to request count changes
            self.event_dispatcher.subscribe(
                callback=self._handle_request_count_change,
                event_filter=create_request_count_filter(),
                subscription_id="dynamic_trigger_request_count"
            )
            
            self.logger.info("✅ Subscribed to monitoring events")
            
        except Exception as e:
            self.logger.error(f"❌ Failed to subscribe to monitoring events: {e}")
    
    def _handle_request_count_change(self, event: BaseEvent):
        """
        Handle request count change events from enhanced monitor.
        
        Args:
            event: Request count change event
        """
        try:
            if not hasattr(event, 'current_count') or not hasattr(event, 'previous_count'):
                return
            
            current_count = event.current_count
            previous_count = event.previous_count
            change_delta = event.change_delta
            
            self.logger.debug(f"🔍 Processing request count change: {previous_count} → {current_count} (Δ{change_delta})")
            
            # Check if any trigger conditions are met
            triggered_conditions = self._evaluate_trigger_conditions(current_count, previous_count)
            
            if triggered_conditions:
                self.logger.info(f"🚀 {len(triggered_conditions)} trigger conditions met")
                
                # Process each triggered condition
                for condition in triggered_conditions:
                    self._process_trigger_condition(condition, current_count, previous_count)
            
        except Exception as e:
            self.logger.error(f"❌ Error handling request count change: {e}")
    
    def _evaluate_trigger_conditions(self, current_count: int, previous_count: int) -> List[TriggerCondition]:
        """
        Evaluate which trigger conditions are met.
        
        Args:
            current_count: Current request count
            previous_count: Previous request count
            
        Returns:
            List of triggered conditions
        """
        triggered_conditions = []
        
        try:
            for condition in self.trigger_conditions:
                if not condition.enabled:
                    continue
                
                # Check cooldown
                if self._is_condition_in_cooldown(condition):
                    continue
                
                # Evaluate condition
                if self._evaluate_single_condition(condition, current_count, previous_count):
                    triggered_conditions.append(condition)
            
            return triggered_conditions
            
        except Exception as e:
            self.logger.error(f"❌ Error evaluating trigger conditions: {e}")
            return []
    
    def _is_condition_in_cooldown(self, condition: TriggerCondition) -> bool:
        """Check if a condition is in cooldown period."""
        if not condition.last_triggered:
            return False
        
        try:
            last_triggered = datetime.fromisoformat(condition.last_triggered)
            cooldown_end = last_triggered + timedelta(seconds=condition.cooldown_seconds)
            return datetime.now() < cooldown_end
        except:
            return False
    
    def _evaluate_single_condition(self, condition: TriggerCondition, current_count: int, previous_count: int) -> bool:
        """Evaluate a single trigger condition."""
        try:
            threshold = condition.threshold_value
            operator = condition.comparison_operator
            
            if operator == "less_than":
                return current_count < threshold
            elif operator == "less_than_or_equal":
                return current_count <= threshold
            elif operator == "greater_than":
                return current_count > threshold
            elif operator == "greater_than_or_equal":
                return current_count >= threshold
            elif operator == "equals":
                return current_count == threshold
            elif operator == "not_equals":
                return current_count != threshold
            elif operator == "decreasing_below":
                return previous_count >= threshold and current_count < threshold
            elif operator == "increasing_above":
                return previous_count <= threshold and current_count > threshold
            
            return False
            
        except Exception as e:
            self.logger.error(f"❌ Error evaluating condition {condition.condition_name}: {e}")
            return False
    
    def _process_trigger_condition(self, condition: TriggerCondition, current_count: int, previous_count: int):
        """
        Process a triggered condition.
        
        Args:
            condition: The triggered condition
            current_count: Current request count
            previous_count: Previous request count
        """
        try:
            start_time = time.time()
            
            # Calculate optimal batch size
            batch_calculation = self.calculate_optimal_batch_size(
                current_count=current_count,
                trigger_type=condition.trigger_type,
                max_batch_size=condition.max_batch_size
            )
            
            # Create trigger event
            trigger_event = TriggerEvent(
                trigger_id=f"{condition.condition_name}_{int(time.time())}",
                trigger_type=condition.trigger_type,
                trigger_condition=condition,
                batch_calculation=batch_calculation,
                trigger_reason=f"Request count {current_count} triggered condition '{condition.condition_name}'",
                suggested_actions=self._generate_suggested_actions(condition, batch_calculation),
                urgency_level=condition.urgency_level,
                timestamp=datetime.now().isoformat(),
                metadata={
                    "current_count": current_count,
                    "previous_count": previous_count,
                    "change_delta": current_count - previous_count
                }
            )
            
            # Execute trigger
            success = self._execute_trigger(trigger_event)
            
            # Update statistics
            processing_time = time.time() - start_time
            self._update_trigger_statistics(trigger_event, success, processing_time)
            
            # Update condition last triggered time
            condition.last_triggered = datetime.now().isoformat()
            
            self.logger.info(f"{'✅' if success else '❌'} Processed trigger {condition.condition_name} "
                           f"(batch size: {batch_calculation.recommended_batch_size}, "
                           f"time: {processing_time:.2f}s)")
            
        except Exception as e:
            self.logger.error(f"❌ Error processing trigger condition {condition.condition_name}: {e}")
    
    def calculate_optimal_batch_size(self, 
                                   current_count: int, 
                                   trigger_type: TriggerType,
                                   max_batch_size: int) -> BatchCalculation:
        """
        Calculate optimal batch size based on current conditions.
        
        Args:
            current_count: Current request count
            trigger_type: Type of trigger
            max_batch_size: Maximum allowed batch size
            
        Returns:
            BatchCalculation with recommended batch size and metadata
        """
        try:
            available_slots = max(0, 10 - current_count)
            
            # Base calculation strategies
            if trigger_type == TriggerType.EMERGENCY_CAPACITY:
                # Emergency: Fill all available slots immediately
                recommended_size = min(available_slots, max_batch_size)
                strategy = "emergency_fill_all"
                confidence = 0.95
                risk = "high"
                
            elif trigger_type == TriggerType.IMMEDIATE_FILL:
                # Immediate: Fill most available slots
                recommended_size = min(available_slots, max_batch_size)
                strategy = "immediate_fill_most"
                confidence = 0.9
                risk = "medium"
                
            elif trigger_type == TriggerType.CAPACITY_AVAILABLE:
                # Available capacity: Fill based on available slots
                if available_slots >= 5:
                    recommended_size = min(available_slots, max_batch_size)
                    strategy = "fill_large_capacity"
                    confidence = 0.85
                elif available_slots >= 2:
                    recommended_size = min(available_slots, max_batch_size // 2)
                    strategy = "fill_medium_capacity"
                    confidence = 0.8
                else:
                    recommended_size = available_slots
                    strategy = "fill_small_capacity"
                    confidence = 0.75
                risk = "low"
                
            elif trigger_type == TriggerType.LOW_REQUEST_COUNT:
                # Low count: Conservative approach
                target_fill = min(8 - current_count, available_slots)
                recommended_size = min(target_fill, max_batch_size)
                strategy = "conservative_fill"
                confidence = 0.8
                risk = "low"
                
            elif trigger_type == TriggerType.PREDICTIVE_UPLOAD:
                # Predictive: Small batch to prepare for future needs
                recommended_size = min(3, available_slots, max_batch_size)
                strategy = "predictive_small_batch"
                confidence = 0.7
                risk = "low"
                
            else:
                # Default strategy
                recommended_size = min(available_slots, max_batch_size // 2)
                strategy = "default_conservative"
                confidence = 0.6
                risk = "medium"
            
            # Ensure minimum constraints
            recommended_size = max(0, min(recommended_size, available_slots, max_batch_size))
            
            # Estimate processing time (rough estimate: 2 hours per request)
            estimated_time = recommended_size * 2.0 if recommended_size > 0 else None
            
            return BatchCalculation(
                recommended_batch_size=recommended_size,
                available_slots=available_slots,
                current_request_count=current_count,
                calculation_strategy=strategy,
                confidence_score=confidence,
                estimated_processing_time=estimated_time,
                risk_assessment=risk
            )
            
        except Exception as e:
            self.logger.error(f"❌ Error calculating optimal batch size: {e}")
            return BatchCalculation(
                recommended_batch_size=0,
                available_slots=0,
                current_request_count=current_count,
                calculation_strategy="error_fallback",
                confidence_score=0.0,
                risk_assessment="unknown"
            )
    
    def _generate_suggested_actions(self, condition: TriggerCondition, batch_calc: BatchCalculation) -> List[str]:
        """Generate suggested actions based on trigger condition and batch calculation."""
        actions = []
        
        try:
            if batch_calc.recommended_batch_size > 0:
                actions.append(f"upload_{batch_calc.recommended_batch_size}_files")
                
                if condition.urgency_level in [TriggerUrgency.CRITICAL, TriggerUrgency.EMERGENCY]:
                    actions.append("increase_monitoring_frequency")
                    actions.append("prioritize_processing")
                
                if batch_calc.risk_assessment == "high":
                    actions.append("monitor_capacity_closely")
                
                if condition.trigger_type == TriggerType.PREDICTIVE_UPLOAD:
                    actions.append("prepare_additional_files")
                
                actions.append("update_capacity_status")
            else:
                actions.append("check_file_availability")
                actions.append("investigate_capacity_constraints")
            
            return actions
            
        except Exception as e:
            self.logger.error(f"❌ Error generating suggested actions: {e}")
            return ["investigate_trigger_error"]
    
    def _execute_trigger(self, trigger_event: TriggerEvent) -> bool:
        """
        Execute a trigger event with rate limiting and error handling.
        
        Args:
            trigger_event: The trigger event to execute
            
        Returns:
            True if execution was successful, False otherwise
        """
        try:
            batch_size = trigger_event.batch_calculation.recommended_batch_size
            
            if batch_size <= 0:
                self.logger.info(f"⏭️ Skipping trigger execution - no files to upload (batch size: {batch_size})")
                return True
            
            # Check rate limits before execution
            if self.config.get("rate_limiting_enabled", True):
                can_execute, wait_time = self._check_rate_limits_for_trigger(trigger_event)
                if not can_execute:
                    self.logger.warning(f"⏳ Trigger execution delayed due to rate limits: {wait_time:.1f}s")
                    # Could implement delayed execution here
                    return False
            
            self.logger.info(f"🚀 Executing trigger: {trigger_event.trigger_type.value} "
                           f"(batch size: {batch_size}, urgency: {trigger_event.urgency_level.value})")
            
            # Store active trigger
            with self.trigger_lock:
                self.active_triggers[trigger_event.trigger_id] = trigger_event
            
            success = False
            
            # Execute with request throttling if enabled
            if self.config.get("request_throttling_enabled", True):
                success = self._execute_trigger_with_throttling(trigger_event, batch_size)
            else:
                success = self._execute_trigger_direct(trigger_event, batch_size)
            
            # Record result with rate limiter
            if self.rate_limiter:
                self.rate_limiter.record_request_result(
                    success=success,
                    response_time=1.0,  # Approximate trigger execution time
                    status_code=200 if success else 500,
                    error_type=None if success else "trigger_execution_failed"
                )
            
            # Notify processing callbacks
            for callback in self.processing_callbacks:
                try:
                    callback(trigger_event, success)
                except Exception as e:
                    self.logger.error(f"❌ Error in processing callback: {e}")
            
            # Remove from active triggers
            with self.trigger_lock:
                self.active_triggers.pop(trigger_event.trigger_id, None)
                self.trigger_history.append(trigger_event)
            
            return success
            
        except Exception as e:
            self.logger.error(f"❌ Error executing trigger: {e}")
            
            # Handle error with error handler
            if self.error_handler:
                try:
                    action, params = self.error_handler.handle_error(
                        e,
                        context={
                            'trigger_id': trigger_event.trigger_id,
                            'trigger_type': trigger_event.trigger_type.value,
                            'batch_size': batch_size
                        }
                    )
                    self.logger.info(f"🔧 Error handler action: {action.value}")
                except Exception as handler_error:
                    self.logger.error(f"❌ Error in error handler: {handler_error}")
            
            return False
    
    def _update_trigger_statistics(self, trigger_event: TriggerEvent, success: bool, processing_time: float):
        """Update trigger statistics."""
        try:
            with self.trigger_lock:
                self.statistics.total_triggers_fired += 1
                
                if success:
                    self.statistics.successful_triggers += 1
                else:
                    self.statistics.failed_triggers += 1
                
                # Update average response time
                total_time = self.statistics.average_response_time * (self.statistics.total_triggers_fired - 1)
                self.statistics.average_response_time = (total_time + processing_time) / self.statistics.total_triggers_fired
                
                # Update triggers by type
                trigger_type_str = trigger_event.trigger_type.value
                self.statistics.triggers_by_type[trigger_type_str] = self.statistics.triggers_by_type.get(trigger_type_str, 0) + 1
                
                self.statistics.last_trigger_time = trigger_event.timestamp
                
                # Update system uptime
                if self.start_time:
                    self.statistics.system_uptime = time.time() - self.start_time
                
                # Store performance metrics
                self.performance_metrics.append({
                    "timestamp": trigger_event.timestamp,
                    "trigger_type": trigger_type_str,
                    "processing_time": processing_time,
                    "success": success,
                    "batch_size": trigger_event.batch_calculation.recommended_batch_size
                })
            
        except Exception as e:
            self.logger.error(f"❌ Error updating trigger statistics: {e}")
    
    def add_processing_callback(self, callback: Callable):
        """
        Add a callback for trigger processing events.
        
        Args:
            callback: Function to call with (trigger_event, success)
        """
        self.processing_callbacks.append(callback)
        self.logger.info("✅ Processing callback added to dynamic trigger system")
    
    def start_system(self):
        """Start the dynamic trigger system."""
        try:
            if self.system_active:
                self.logger.warning("⚠️ Dynamic trigger system is already active")
                return
            
            self.start_time = time.time()
            self.system_active = True
            
            # Subscribe to monitoring events
            self.subscribe_to_monitoring_events()
            
            self.logger.info("🚀 Dynamic trigger system started")
            
        except Exception as e:
            self.logger.error(f"❌ Failed to start dynamic trigger system: {e}")
    
    def stop_system(self):
        """Stop the dynamic trigger system."""
        try:
            if not self.system_active:
                return
            
            self.system_active = False
            
            # Clear active triggers
            with self.trigger_lock:
                self.active_triggers.clear()
            
            self.logger.info("🛑 Dynamic trigger system stopped")
            
        except Exception as e:
            self.logger.error(f"❌ Error stopping dynamic trigger system: {e}")
    
    def get_system_status(self) -> Dict[str, Any]:
        """
        Get current system status and statistics.
        
        Returns:
            Dictionary with system status information
        """
        try:
            with self.trigger_lock:
                return {
                    "system_active": self.system_active,
                    "start_time": datetime.fromtimestamp(self.start_time).isoformat() if self.start_time else None,
                    "statistics": asdict(self.statistics),
                    "active_triggers": len(self.active_triggers),
                    "trigger_conditions": len([c for c in self.trigger_conditions if c.enabled]),
                    "configuration": self.config,
                    "integration_status": {
                        "enhanced_monitor": self.enhanced_monitor is not None,
                        "capacity_manager": self.capacity_manager is not None,
                        "batch_system": self.batch_system is not None,
                        "queue_manager": self.queue_manager is not None
                    },
                    "generated_at": datetime.now().isoformat()
                }
                
        except Exception as e:
            self.logger.error(f"❌ Error getting system status: {e}")
            return {"error": str(e), "generated_at": datetime.now().isoformat()}
    
    def get_performance_analytics(self) -> Dict[str, Any]:
        """
        Get performance analytics and insights.
        
        Returns:
            Dictionary with performance analytics
        """
        try:
            with self.trigger_lock:
                # Calculate performance metrics
                if not self.performance_metrics:
                    return {"message": "No performance data available", "generated_at": datetime.now().isoformat()}
                
                metrics = list(self.performance_metrics)
                
                # Success rate analysis
                successful_triggers = len([m for m in metrics if m["success"]])
                success_rate = (successful_triggers / len(metrics)) * 100 if metrics else 0
                
                # Response time analysis
                response_times = [m["processing_time"] for m in metrics]
                avg_response_time = sum(response_times) / len(response_times) if response_times else 0
                max_response_time = max(response_times) if response_times else 0
                min_response_time = min(response_times) if response_times else 0
                
                # Batch size analysis
                batch_sizes = [m["batch_size"] for m in metrics]
                avg_batch_size = sum(batch_sizes) / len(batch_sizes) if batch_sizes else 0
                
                # Trigger type distribution
                type_distribution = {}
                for metric in metrics:
                    trigger_type = metric["trigger_type"]
                    type_distribution[trigger_type] = type_distribution.get(trigger_type, 0) + 1
                
                return {
                    "performance_summary": {
                        "total_triggers": len(metrics),
                        "success_rate": success_rate,
                        "average_response_time": avg_response_time,
                        "max_response_time": max_response_time,
                        "min_response_time": min_response_time,
                        "average_batch_size": avg_batch_size
                    },
                    "trigger_type_distribution": type_distribution,
                    "recent_performance": metrics[-10:],  # Last 10 triggers
                    "system_uptime": self.statistics.system_uptime,
                    "generated_at": datetime.now().isoformat()
                }
                
        except Exception as e:
            self.logger.error(f"❌ Error getting performance analytics: {e}")
            return {"error": str(e), "generated_at": datetime.now().isoformat()}
    
    def cleanup(self):
        """Clean up the dynamic trigger system."""
        self.logger.info("🧹 Cleaning up DynamicTriggerSystem...")
        
        # Stop system
        self.stop_system()
        
        # Clear data structures
        with self.trigger_lock:
            self.active_triggers.clear()
            self.trigger_history.clear()
            self.performance_metrics.clear()
            self.processing_callbacks.clear()
        
    
    def _handle_rate_limit_event(self, event_type: str, **kwargs):
        """Handle rate limit events."""
        self.logger.debug(f"🚦 Rate limit event: {event_type}")
        
        if event_type == "rate_limit_hit":
            # Temporarily reduce trigger aggressiveness
            self._adjust_trigger_conditions_for_rate_limit()
        elif event_type == "rate_limit_recovered":
            # Restore normal trigger conditions
            self._restore_trigger_conditions()
    
    def _handle_error_event(self, error_occurrence, action, action_params):
        """Handle error events from error handler."""
        self.logger.debug(f"🔧 Error event: {error_occurrence.error_pattern.name} -> {action.value}")
        
        # Adjust trigger behavior based on error patterns
        if error_occurrence.error_pattern.category.value == "rate_limit":
            self._adjust_trigger_conditions_for_rate_limit()
        elif error_occurrence.error_pattern.category.value == "service_unavailable":
            self._pause_triggers_temporarily()
    
    def _handle_throttling_event(self, event_type: str, request):
        """Handle throttling events from request throttler."""
        self.logger.debug(f"⏱️ Throttling event: {event_type} for {request.request_id}")
        
        # Update statistics based on throttling events
        if event_type == "completed":
            if request.status.value == "completed":
                self.statistics.successful_triggers += 1
            else:
                self.statistics.failed_triggers += 1
    
    def _adjust_trigger_conditions_for_rate_limit(self):
        """Adjust trigger conditions when rate limits are hit."""
        with self.trigger_lock:
            for condition in self.trigger_conditions:
                # Increase cooldown periods
                condition.cooldown_seconds = min(condition.cooldown_seconds * 1.5, 300)
                # Reduce max batch sizes
                condition.max_batch_size = max(condition.max_batch_size // 2, 1)
        
        self.logger.info("🔧 Adjusted trigger conditions for rate limiting")
    
    def _restore_trigger_conditions(self):
        """Restore normal trigger conditions after rate limit recovery."""
        # Reinitialize conditions to defaults
        self.trigger_conditions = self._initialize_trigger_conditions()
        self.logger.info("🔧 Restored normal trigger conditions")
    
    def _pause_triggers_temporarily(self):
        """Temporarily pause trigger processing."""
        # This could be implemented to pause the system during service outages
        self.logger.warning("⏸️ Temporarily pausing triggers due to service issues")
    
    def _check_rate_limits_for_trigger(self, trigger_event: TriggerEvent) -> Tuple[bool, float]:
        """
        Check if trigger can be executed within rate limits.
        
        Args:
            trigger_event: The trigger event to check
            
        Returns:
            Tuple of (can_execute, wait_time_seconds)
        """
        if not self.rate_limiter:
            return True, 0.0
        
        # Check if we can make the requests needed for this trigger
        batch_size = trigger_event.batch_calculation.recommended_batch_size
        
        # For batch operations, we need to consider multiple requests
        total_wait_time = 0.0
        
        for i in range(batch_size):
            can_request, wait_time = self.rate_limiter.can_make_request()
            if not can_request:
                total_wait_time = max(total_wait_time, wait_time)
        
        return total_wait_time == 0.0, total_wait_time
    
    def _execute_trigger_with_throttling(self, trigger_event: TriggerEvent, batch_size: int) -> bool:
        """Execute trigger using request throttling system."""
        try:
            # Submit trigger execution as a throttled request
            from automation.request_throttler import RequestPriority
            
            # Map trigger urgency to request priority
            priority_mapping = {
                TriggerUrgency.LOW: RequestPriority.LOW,
                TriggerUrgency.NORMAL: RequestPriority.NORMAL,
                TriggerUrgency.HIGH: RequestPriority.HIGH,
                TriggerUrgency.CRITICAL: RequestPriority.CRITICAL,
                TriggerUrgency.EMERGENCY: RequestPriority.EMERGENCY
            }
            
            priority = priority_mapping.get(trigger_event.urgency_level, RequestPriority.NORMAL)
            
            # Start throttler if not running
            if not self.request_throttler.running:
                self.request_throttler.start()
            
            # Submit the trigger execution as a throttled request
            request_id = self.request_throttler.submit_request(
                request_func=self._execute_trigger_direct,
                args=(trigger_event, batch_size),
                priority=priority,
                timeout=300.0,  # 5 minute timeout
                context={
                    'trigger_id': trigger_event.trigger_id,
                    'trigger_type': trigger_event.trigger_type.value
                }
            )
            
            self.logger.debug(f"🎯 Trigger execution queued with throttler: {request_id}")
            
            # For now, assume success (async execution)
            # In a real implementation, you might want to wait for completion
            return True
            
        except Exception as e:
            self.logger.error(f"❌ Error in throttled trigger execution: {e}")
            return False
    
    def _execute_trigger_direct(self, trigger_event: TriggerEvent, batch_size: int) -> bool:
        """Execute trigger directly without throttling."""
        success = False
        
        # Try capacity manager first (preferred method)
        if self.capacity_manager:
            try:
                upload_result = self.capacity_manager.trigger_upload_automation(max_files=batch_size)
                success = upload_result.success
                
                if success:
                    self.logger.info(f"✅ Capacity manager upload successful: {upload_result.message}")
                else:
                    self.logger.warning(f"⚠️ Capacity manager upload failed: {upload_result.message}")
                    
            except Exception as e:
                self.logger.error(f"❌ Error in capacity manager upload: {e}")
        
        # Fallback to batch system auto-upload
        if not success and self.batch_system and hasattr(self.batch_system, '_auto_upload_new_files'):
            try:
                self.batch_system._auto_upload_new_files(batch_size)
                success = True
                self.logger.info(f"✅ Batch system auto-upload triggered for {batch_size} files")
            except Exception as e:
                self.logger.error(f"❌ Error in batch system auto-upload: {e}")
        
        return success
        self.logger.info("✅ DynamicTriggerSystem cleanup completed")


def create_dynamic_trigger_system(enhanced_monitor: Optional[EnhancedRequestMonitor] = None,
                                capacity_manager: Optional[CapacityManager] = None,
                                event_dispatcher: Optional[EventDispatcher] = None,
                                config: Optional[Dict[str, Any]] = None) -> DynamicTriggerSystem:
    """
    Factory function to create a DynamicTriggerSystem.
    
    Args:
        enhanced_monitor: Enhanced request monitor for event subscription
        capacity_manager: Capacity manager for upload automation
        event_dispatcher: Event dispatcher for notifications
        config: Configuration dictionary
        
    Returns:
        DynamicTriggerSystem instance
    """
    return DynamicTriggerSystem(
        enhanced_monitor=enhanced_monitor,
        capacity_manager=capacity_manager,
        event_dispatcher=event_dispatcher,
        config=config
    )


if __name__ == "__main__":
    # Example usage and testing
    import argparse
    
    parser = argparse.ArgumentParser(description='Dynamic Trigger System')
    parser.add_argument('--start-system', action='store_true',
                       help='Start the dynamic trigger system')
    parser.add_argument('--status', action='store_true',
                       help='Show system status')
    parser.add_argument('--analytics', action='store_true',
                       help='Show performance analytics')
    parser.add_argument('--test-triggers', action='store_true',
                       help='Test trigger conditions')
    
    args = parser.parse_args()
    
    # Create dynamic trigger system
    trigger_system = create_dynamic_trigger_system()
    
    try:
        if args.start_system:
            print("=== Starting Dynamic Trigger System ===")
            trigger_system.start_system()
            
            # Keep running until interrupted
            try:
                while trigger_system.system_active:
                    time.sleep(1)
            except KeyboardInterrupt:
                print("\nStopping dynamic trigger system...")
                trigger_system.stop_system()
        
        elif args.status:
            print("=== Dynamic Trigger System Status ===")
            status = trigger_system.get_system_status()
            print(json.dumps(status, indent=2))
        
        elif args.analytics:
            print("=== Performance Analytics ===")
            analytics = trigger_system.get_performance_analytics()
            print(json.dumps(analytics, indent=2))
        
        elif args.test_triggers:
            print("=== Testing Trigger Conditions ===")
            
            # Test trigger evaluation
            test_conditions = [
                (5, 8),   # Low count trigger
                (2, 5),   # Emergency trigger
                (8, 10),  # Capacity available
                (3, 3),   # No change
            ]
            
            for current, previous in test_conditions:
                print(f"\nTesting: {previous} → {current}")
                triggered = trigger_system._evaluate_trigger_conditions(current, previous)
                print(f"Triggered conditions: {len(triggered)}")
                for condition in triggered:
                    print(f"  - {condition.condition_name} ({condition.trigger_type.value})")
        
        else:
            parser.print_help()
            print("\n" + "="*60)
            print("DYNAMIC TRIGGER SYSTEM EXAMPLES")
            print("="*60)
            print("# Start dynamic trigger system:")
            print("python automation/dynamic_trigger_system.py --start-system")
            print("\n# Show system status:")
            print("python automation/dynamic_trigger_system.py --status")
            print("\n# Show performance analytics:")
            print("python automation/dynamic_trigger_system.py --analytics")
            print("\n# Test trigger conditions:")
            print("python automation/dynamic_trigger_system.py --test-triggers")
            print("="*60)
            
    except Exception as e:
        print(f"Error: {e}")
        if hasattr(trigger_system, 'system_active') and trigger_system.system_active:
            trigger_system.stop_system()
    finally:
        trigger_system.cleanup()